XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXX FFFFFX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
       FFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
