XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX  FFFFFFF XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
       FFFFFFF

    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXX FFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
          XXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXX XX XXXXXXX XXXXXX XXXXXXXXXX XX XXXXXX XX XXXXXX XXXXX XXXXXXX XX XXXX XX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXX
