XXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX  FFFFFFF XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX FFFFFX XXXXXXXXXXXXX XXXXXXXXXXXXXX
       FFFFFFF

    XXXXX
    XXXX XXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXX
      
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX
          XX XXXXXXXXX XXXXX  FFFFFFFFFFFFXXXXXX XX XXXXXXX XXXXXX X XXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXX X XXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX
      XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXX X XXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXX X XXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           FFFFFFFFFFFFFFF
        XXXXXX
      XXXXXX
    XXXXXX XXX
  XXXXXX
XXXXX
