XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXX XXXXX XXXXXX
    XXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX
  XXXX
    XXXX XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXX
            XXXX
          XXXXX
          XXXX
            XX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
            XXXX
          XXXXX
        XXXXX
    XXXXXX XXX
XXXXXX
