# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('inprogress', 'inprogress'), ('created', 'created'), ('resolved', 'resolved'), ('stuck', 'stuck')], default='created', max_length=50)),
                ('tentresdt', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=50)),
                ('result', models.CharField(choices=[('resolved', 'resolved'), ('partial', 'partial'), ('parked', 'parked')], max_length=50, null=True)),
                ('resultComments', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.models.getcontentFilePath)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(max_length=300, null=True)),
                ('attachment', models.FileField(null=True, upload_to=projects.models.getProjectsUploadsPath)),
                ('mediaType', models.CharField(choices=[('onlineVideo', 'onlineVideo'), ('video', 'video'), ('image', 'image'), ('onlineImage', 'onlineImage'), ('doc', 'doc')], default='image', max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsUploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('projectClosed', models.BooleanField(default=False)),
                ('costCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectCostcenter', to='finance.CostCenter')),
                ('expenseSheets', models.ManyToManyField(related_name='project', to='finance.ExpenseSheet')),
                ('files', models.ManyToManyField(related_name='projects', to='projects.media')),
                ('invoices', models.ManyToManyField(related_name='projects', to='finance.ExpenseSheet')),
                ('ourBoundInvoices', models.ManyToManyField(related_name='projectOutBoundInvoice', to='finance.OutBoundInvoice')),
                ('team', models.ManyToManyField(related_name='projectsInvolvedIn', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsInitiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPettyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200, null=True)),
                ('attachment', models.FileField(null=True, upload_to=projects.models.getPettyCashInvoicePath)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pettyCashExpenses', to='finance.Account')),
                ('createdUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userExpense', to=settings.AUTH_USER_MODEL)),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pettyExpense', to='finance.ExpenseHeading')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('GRN', 'GRN'), ('Approved', 'Approved')], default='created', max_length=30)),
                ('isInvoice', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('personName', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('pin_status', models.CharField(default='1', max_length=2)),
                ('poNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('quoteNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('quoteDate', models.DateField(blank=True, null=True)),
                ('deliveryDate', models.DateField(blank=True, null=True)),
                ('paymentDueDate', models.DateField(null=True)),
                ('gstIn', models.CharField(max_length=30, null=True)),
                ('terms', models.TextField(blank=True, max_length=500, null=True)),
                ('invoiceTerms', models.TextField(blank=True, max_length=500, null=True)),
                ('accNo', models.CharField(max_length=30, null=True)),
                ('ifsc', models.CharField(max_length=30, null=True)),
                ('bankName', models.CharField(max_length=30, null=True)),
                ('bussinessunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderBusinessunit', to='organization.Unit')),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseCostcenter', to='finance.CostCenter')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderProject', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('tax', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('receivedQty', models.PositiveIntegerField(default=0)),
                ('productMeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmeta', to='clientRelationships.ProductMeta')),
                ('purchaseorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='projects.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='timelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('message', 'message'), ('file', 'file'), ('system', 'system')], default='message', max_length=50)),
                ('text', models.TextField(max_length=2000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsTimelineItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projectComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            bases=('projects.comment',),
        ),
        migrations.AddField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsIssue', to='projects.project'),
        ),
        migrations.AddField(
            model_name='issues',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsIssueResponsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.media'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
