# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='responder',
        ),
        migrations.DeleteModel(
            name='issues',
        ),
    ]
