# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='result',
            field=models.CharField(choices=[('resolved', 'resolved'), ('partial', 'partial'), ('parked', 'parked')], max_length=50),
        ),
    ]
