# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20181102_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='resultComments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50),
        ),
    ]
