# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20181112_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='issues',
        ),
    ]
