# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20190110_1303'),
        ('projects', '0018_auto_20181129_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPettyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200, null=True)),
                ('attachment', models.FileField(null=True, upload_to=projects.models.getPettyCashInvoicePath)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pettyCashExpenses', to='finance.Account')),
                ('heading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pettyExpense', to='finance.ExpenseHeading')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='costCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='finance.CostCenter'),
        ),
        migrations.AddField(
            model_name='project',
            name='expenseSheets',
            field=models.ManyToManyField(related_name='project', to='finance.ExpenseSheet'),
        ),
        migrations.AddField(
            model_name='projectpettyexpense',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project'),
        ),
    ]
