# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20190110_1342'),
        ('projects', '0019_auto_20190110_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoices',
            field=models.ManyToManyField(related_name='projects', to='finance.ExpenseSheet'),
        ),
    ]
