# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180614_0401'),
        ('finance', '0038_auto_20190114_0516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_project_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('personName', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('Approved', 'Approved'), ('Final', 'Final')], default='created', max_length=5)),
                ('poNumber', models.CharField(max_length=500, null=True)),
                ('quoteNumber', models.CharField(max_length=500, null=True)),
                ('deliveryDate', models.DateField(null=True)),
                ('terms', models.CharField(max_length=500, null=True)),
                ('bussinessunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderBusinessunit', to='organization.Unit')),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseCostcenter', to='finance.CostCenter')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderProject', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
