# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectpettyexpense_createduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpettyexpense',
            old_name='ammount',
            new_name='amount',
        ),
    ]
