# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='isInvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderqty',
            name='purchaseorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='projects.PurchaseOrder'),
        ),
    ]
