# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_merge_20190114_0713'),
        ('projects', '0023_auto_20190115_0745'),
    ]

    operations = [
    ]
