# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0007_contract_totaltax'),
        ('projects', '0024_merge_20190115_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderqty',
            name='hsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmeta', to='clientRelationships.ProductMeta'),
        ),
        migrations.AddField(
            model_name='purchaseorderqty',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderqty',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
