# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20190116_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quoteDate',
            field=models.DateField(null=True),
        ),
    ]
