# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_purchaseorder_quotedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='poNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
