# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20190116_1300'),
        ('projects', '0026_auto_20190116_1029'),
    ]

    operations = [
    ]
