# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20190117_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gstIn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paymentDueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pin_status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='poNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quoteNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Received', 'Received'), ('NotReceivedAndArchived', 'NotReceivedAndArchived'), ('Reconciled', 'Reconciled')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='terms',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
