# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20190124_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderqty',
            name='receivedQty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('Approved', 'Approved')], default='created', max_length=30),
        ),
    ]
