# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20190127_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='accNo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bankName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ifsc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
