# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0007_contract_totaltax'),
        ('projects', '0032_auto_20190127_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderqty',
            name='productMeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmeta', to='clientRelationships.ProductMeta'),
        ),
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
