# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20190127_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='invoiceTerms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quoteDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quoteNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='terms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
