# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20190127_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('GRN', 'GRN'), ('Approved', 'Approved')], default='created', max_length=30),
        ),
    ]
