# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=400)),
                ('mobile', models.CharField(max_length=15)),
                ('telephone', models.PositiveIntegerField(default=0, null=True)),
                ('fax', models.PositiveIntegerField(default=0, null=True)),
                ('picture', models.FileField(null=True, upload_to=organization.models.getDepartmentsLogoAttachmentPath)),
                ('contacts', models.ManyToManyField(related_name='departmentsHeading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('logo', models.FileField(null=True, upload_to=organization.models.getDivisionLogoAttachmentPath)),
                ('gstin', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=200)),
                ('l1', models.CharField(max_length=200, null=True)),
                ('l2', models.CharField(max_length=200, null=True)),
                ('contacts', models.ManyToManyField(related_name='divisionsHeading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('yearly', 'yearly'), ('quaterly', 'quaterly'), ('monthly', 'monthly'), ('weekly', 'weekly'), ('daily', 'daily')], default='yearly', max_length=20)),
                ('weightage', models.IntegerField(null=True)),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAAssigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KRAProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAAwarded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='responsibilities', to='organization.Departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilitiesCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='organization.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('pincode', models.PositiveIntegerField()),
                ('l1', models.CharField(max_length=200, null=True)),
                ('l2', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('contacts', models.ManyToManyField(related_name='unitsHeading', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.Division')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='kra',
            name='progress',
            field=models.ManyToManyField(blank=True, related_name='KRA', to='organization.KRAProgress'),
        ),
        migrations.AddField(
            model_name='kra',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAs', to='organization.Responsibility'),
        ),
        migrations.AddField(
            model_name='kra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departments',
            name='unit',
            field=models.ManyToManyField(related_name='departmentsUnits', to='organization.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='kra',
            unique_together=set([('user', 'responsibility')]),
        ),
    ]
