# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_service_contactperson'),
        ('organization', '0008_auto_20180614_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='roles', to='ERP.application'),
        ),
    ]
