# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_role_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='roleApplications', to='ERP.application'),
        ),
    ]
