# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('interviewDate', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('suitable', 'suitable'), ('un-suitable', 'un-suitable'), ('recommand-other-job', 'recommand-other-job')], default='created', max_length=15)),
                ('mode', models.CharField(choices=[('online', 'online'), ('telephonic', 'telephonic'), ('face-to-face', 'face-to-face')], default='online', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('resume', models.FileField(null=True, upload_to=organization.models.getDepartmentsLogoAttachmentPath)),
                ('coverletter', models.CharField(max_length=4000, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Screening', 'Screening'), ('SelfAssesmenent', 'SelfAssesmenent'), ('TechicalInterview', 'TechicalInterviewing'), ('HRInterview', 'HRInterview'), ('Shortlisted', 'Shortlisted'), ('Negotiation', 'Negotiation'), ('Onboarding', 'Onboarding'), ('Closed', 'Closed')], default='Created', max_length=15)),
                ('aggree', models.BooleanField(default=False)),
                ('joiningDate', models.DateField(null=True)),
                ('basic', models.PositiveIntegerField(default=0)),
                ('hra', models.PositiveIntegerField(default=0)),
                ('lta', models.PositiveIntegerField(default=0)),
                ('special', models.PositiveIntegerField(default=0)),
                ('taxSlab', models.PositiveIntegerField(default=0)),
                ('adHoc', models.PositiveIntegerField(default=0)),
                ('al', models.PositiveIntegerField(default=0)),
                ('ml', models.PositiveIntegerField(default=0)),
                ('adHocLeaves', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('notice', models.PositiveIntegerField(default=0)),
                ('probation', models.PositiveIntegerField(default=0)),
                ('off', models.BooleanField(default=True)),
                ('probationNotice', models.PositiveIntegerField(default=0)),
                ('noticePeriodRecovery', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Intern', max_length=15)),
                ('skill', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('maximumCTC', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Active', 'Active'), ('Closed', 'Closed')], default='Created', max_length=15)),
                ('contacts', models.ManyToManyField(related_name='jobHeading', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_a', to='organization.Departments')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_a', to='organization.Role')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_a', to='organization.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to='recruitment.Jobs'),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.JobApplication'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviwer', to=settings.AUTH_USER_MODEL),
        ),
    ]
