# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('ifsc', models.CharField(max_length=15)),
                ('bank', models.CharField(max_length=50)),
                ('bankAddress', models.TextField(max_length=500)),
                ('personal', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0)),
                ('authorizedSignaturies', models.ManyToManyField(blank=True, related_name='checkingAccounts', to=settings.AUTH_USER_MODEL)),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsManaging', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costCenters', to='organization.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costCenterAccount', to='finance.Account')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userDesignationUnit', to='organization.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], default='No', max_length=5)),
                ('approvalMatrix', models.PositiveSmallIntegerField(default=1)),
                ('approvalStage', models.PositiveSmallIntegerField(default=0)),
                ('dispensed', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=30, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('totalDisbursed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('referenceID', models.CharField(max_length=30)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5)),
                ('dated', models.DateField()),
                ('attachment', models.FileField(null=True, upload_to=finance.models.getInflowAttachmentsPath)),
                ('description', models.TextField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('fromBank', models.CharField(max_length=30, null=True)),
                ('chequeNo', models.CharField(max_length=30, null=True)),
                ('mode', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('wire', 'wire')], default='cash', max_length=20)),
                ('gstCollected', models.FloatField(default=0)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inflow', to='ERP.service')),
                ('toAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflowCredits', to='finance.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflowsTransacted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(default=0, max_length=100)),
                ('qtyAdded', models.CharField(default=0, max_length=100)),
                ('rate', models.FloatField(default=1)),
                ('refurnished', models.CharField(default=0, max_length=100)),
                ('refurnishedAdded', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(default=0, max_length=100)),
                ('refurnished', models.CharField(default=0, max_length=100)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorylog', to='finance.Inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5)),
                ('dated', models.DateField()),
                ('attachment', models.FileField(null=True, upload_to=finance.models.getInvoicesPath)),
                ('description', models.TextField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('dispensed', models.BooleanField(default=False)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeInvoice', to='finance.ExpenseHeading')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.ExpenseSheet')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Received', 'Received'), ('NotReceivedAndArchived', 'NotReceivedAndArchived'), ('Reconciled', 'Reconciled')], default='created', max_length=30)),
                ('isInvoice', models.BooleanField(default=False)),
                ('poNumber', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('personName', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('pin_status', models.CharField(default='1', max_length=2)),
                ('deliveryDate', models.DateField(null=True)),
                ('payDueDate', models.DateField(null=True)),
                ('gstIn', models.CharField(max_length=30, null=True)),
                ('bussinessunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundBusinessunit', to='organization.Unit')),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundCostcenter', to='finance.CostCenter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundInvoiceUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundInvoiceQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('tax', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('hsn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundQtyMeta', to='clientRelationships.ProductMeta')),
                ('outBound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundQty', to='finance.OutBoundInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('externalReferenceID', models.CharField(max_length=30, null=True)),
                ('externalConfirmationID', models.CharField(max_length=30, null=True)),
                ('api', models.CharField(max_length=20, null=True)),
                ('apiCallParams', models.CharField(max_length=1500, null=True)),
                ('fromAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='finance.Account')),
                ('toAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='finance.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to=finance.models.getInvoiceUploadPath)),
                ('settled', models.BooleanField(default=False)),
                ('disbursedOn', models.DateTimeField(null=True)),
                ('approvedOn', models.DateTimeField(null=True)),
                ('dueDate', models.DateField()),
                ('dated', models.DateField()),
                ('amount', models.FloatField(default=0, null=True)),
                ('approved', models.NullBooleanField()),
                ('disbursed', models.NullBooleanField()),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceApprovedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contactPerson', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('paymentTerm', models.PositiveIntegerField(default=0, null=True)),
                ('contentDocs', models.FileField(blank=True, null=True, upload_to=finance.models.getcontentDocsPath)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorprofiles', to='ERP.service')),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=100, unique=True)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('vendorProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorservices', to='finance.VendorProfile')),
            ],
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendorProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorInvoices', to='finance.VendorProfile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directInvoicePayments', to='finance.Transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesheet',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenseSheet', to='finance.Transaction'),
        ),
        migrations.AddField(
            model_name='expensesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
