# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_vendorprofile_vendorservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='service',
        ),
        migrations.RemoveField(
            model_name='vendorservice',
            name='vendorProfile',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
        migrations.DeleteModel(
            name='VendorService',
        ),
    ]
