# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_vendorprofile_vendorservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
