# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_vendorprofile_vendorservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='contactPerson',
            field=models.CharField(max_length=100),
        ),
    ]
