# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20181114_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='vendor',
        ),
    ]
