# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_vendorprofile_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='invoice',
            field=models.FileField(null=True, upload_to=finance.models.getInvoiceUploadPath),
        ),
    ]
