# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_vendorservice_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorservice',
            name='invoice',
        ),
    ]
