# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0011_remove_vendorservice_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(null=True, upload_to=finance.models.getInvoiceUploadPath)),
                ('settled', models.BooleanField(default=False)),
                ('disbursedOn', models.DateTimeField(null=True)),
                ('approvedOn', models.DateTimeField(null=True)),
                ('dueDate', models.DateTimeField()),
                ('Dated', models.DateField()),
                ('amount', models.PositiveIntegerField(default=0, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('disbursed', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('vendorService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorInvoices', to='finance.VendorService')),
            ],
        ),
    ]
