# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20181120_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
