# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20181120_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinvoice',
            old_name='Dated',
            new_name='dated',
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='approvedOn',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='disbursedOn',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
