# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20181120_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='vendorService',
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendorProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorInvoices', to='finance.VendorProfile'),
        ),
    ]
