# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20181120_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='vendorProfile',
        ),
        migrations.DeleteModel(
            name='VendorInvoice',
        ),
    ]
