# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0017_auto_20181120_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(null=True, upload_to=finance.models.getInvoiceUploadPath)),
                ('settled', models.BooleanField(default=False)),
                ('disbursedOn', models.DateField(null=True)),
                ('approvedOn', models.DateField(null=True)),
                ('dueDate', models.DateField()),
                ('dated', models.DateField()),
                ('amount', models.FloatField(default=0, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('disbursed', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('vendorProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorInvoices', to='finance.VendorProfile')),
            ],
        ),
    ]
