# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_vendorinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='disbursed',
            field=models.NullBooleanField(),
        ),
    ]
