# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20181121_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='approvedOn',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
