# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20181121_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='approvedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='disbursedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
