# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_auto_20181121_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='invoice',
            field=models.FileField(upload_to=finance.models.getInvoiceUploadPath),
        ),
    ]
