# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20181224_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='project',
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeInvoice', to='finance.ExpenseHeading'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.ExpenseSheet'),
        ),
    ]
