# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20190110_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesheet',
            name='totalDisbursed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directInvoicePayments', to='finance.Transaction'),
        ),
    ]
