# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20190111_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, unique=True)),
                ('qty', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
