# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20190111_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ammount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='externalConfirmationID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='externalReferenceID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
