# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20190111_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderqty',
            name='productorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='finance.PurchaseOrder'),
        ),
    ]
