# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_purchaseorderqty_productorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderqty',
            old_name='productorder',
            new_name='purchaseorder',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='personName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
