# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20190111_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
