# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_auto_20190111_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='balance',
        ),
    ]
