# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20190111_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='personName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderqty',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
