# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20190111_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('Approved', 'Approved'), ('Final', 'Final')], default='created', max_length=5),
        ),
    ]
