# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20190111_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deliveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='poNumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quoteNumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
