# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20190111_1348'),
        ('finance', '0030_remove_inflow_balance'),
    ]

    operations = [
    ]
