# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_merge_20190112_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='gstCollected',
            field=models.FloatField(default=0),
        ),
    ]
