# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180614_0401'),
        ('finance', '0035_inflow_gstcollected'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costCenters', to='organization.Unit'),
        ),
    ]
