# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180614_0401'),
        ('finance', '0036_account_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userDesignationUnit', to='organization.Unit'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costCenterAccount', to='finance.Account'),
        ),
    ]
