# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_auto_20190114_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='bussinessunit',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='costcenter',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseorderqty',
            name='purchaseorder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderQty',
        ),
    ]
