# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_auto_20190114_0514'),
        ('finance', '0039_auto_20190114_0521'),
    ]

    operations = [
    ]
