# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180614_0401'),
        ('clientRelationships', '0007_contract_totaltax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0040_merge_20190114_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutBoundInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('Approved', 'Approved'), ('Final', 'Final')], default='created', max_length=12)),
                ('isInvoice', models.BooleanField(default=False)),
                ('poNumber', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('personName', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('pin_status', models.CharField(default='1', max_length=2)),
                ('deliveryDate', models.DateField(null=True)),
                ('payDueDate', models.DateField(null=True)),
                ('gstIn', models.CharField(max_length=30, null=True)),
                ('bussinessunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundBusinessunit', to='organization.Unit')),
                ('costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundCostcenter', to='finance.CostCenter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundInvoiceUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundInvoiceQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1)),
                ('tax', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('hsn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundQtyMeta', to='clientRelationships.ProductMeta')),
                ('outBound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outBoundQty', to='finance.OutBoundInvoice')),
            ],
        ),
    ]
