# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0041_outboundinvoice_outboundinvoiceqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundinvoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Received', 'Received'), ('NotReceivedAndArchived', 'NotReceivedAndArchived'), ('Reconciled', 'Reconciled')], default='created', max_length=30),
        ),
    ]
