# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_auto_20190123_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundinvoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Sent', 'Sent'), ('Approved', 'Approved')], default='created', max_length=30),
        ),
    ]
