# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_auto_20190127_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundinvoiceqty',
            name='receivedQty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
