# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_inventory_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='qtyAdded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='refurnished',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='refurnishedAdded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='refurnished',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
