# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_auto_20190131_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='refurnished',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='refurnishedAdded',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='refurnished',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
