# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20181208_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(max_length=50)),
                ('timeDuration', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('demoRequested', models.BooleanField(default=False)),
                ('enterpriseContact', models.BooleanField(default=False)),
                ('blogsSubscribed', models.BooleanField(default=False)),
                ('isAgent', models.BooleanField(default=False)),
                ('ipAddress', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyHolidays',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='contactPerson',
        ),
        migrations.RemoveField(
            model_name='service',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.AddField(
            model_name='activity',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorActivity', to='ERP.Visitor'),
        ),
    ]
