# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20181211_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
