# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20181211_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timeDuration',
            field=models.FloatField(default=0.0),
        ),
    ]
