# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0004_service_contactperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contactPerson',
        ),
        migrations.AddField(
            model_name='service',
            name='contactPerson',
            field=models.ManyToManyField(blank=True, related_name='servicesContactPerson', to=settings.AUTH_USER_MODEL),
        ),
    ]
