# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20181211_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='apiGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
