# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0005_auto_20180922_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='servicesAdvisors', to=settings.AUTH_USER_MODEL),
        ),
    ]
