# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20180922_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='customerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
