# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20181113_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
