# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0006_service_advisors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('advisors', models.ManyToManyField(blank=True, related_name='advisor_team', to=settings.AUTH_USER_MODEL)),
                ('quality_check', models.ManyToManyField(blank=True, related_name='qc_team', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ManyToManyField(blank=True, related_name='tl_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
