# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20181224_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
