# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_service_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=35, null=True)),
                ('city', models.CharField(max_length=35, null=True)),
                ('country', models.CharField(default='India', max_length=35)),
                ('pincode', models.CharField(max_length=7, null=True)),
                ('pin_status', models.CharField(default='1', max_length=2)),
            ],
        ),
    ]
