# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_visitor_apigenerated'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(max_length=99999)),
            ],
        ),
    ]
