# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_service', to='ERP.Teams'),
        ),
    ]
