# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_service_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='team',
        ),
        migrations.AddField(
            model_name='teams',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='teams', to='ERP.service'),
        ),
    ]
