# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_remove_sessionimage_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors24profile',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
