# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20180802_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='params',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='state',
        ),
    ]
