# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_auto_20180807_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerBannerPage', to='ecommerce.Pages'),
        ),
    ]
