# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_offerbanner_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='url',
            new_name='pageurl',
        ),
    ]
