# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_genericproduct_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
