# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_address_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
