# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_supportfeed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pincodes', models.PositiveIntegerField()),
            ],
        ),
    ]
