# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=35, null=True)),
                ('city', models.CharField(max_length=35, null=True)),
                ('pincode', models.CharField(max_length=7, null=True)),
            ],
        ),
    ]
