# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_genericpincode_pin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfeed',
            name='invoiceNo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
