# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0051_supportfeed_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to=ecommerce.models.getEcommerceBannerUploadPath)),
                ('cartImage', models.ImageField(upload_to=ecommerce.models.getEcommerceBannerUploadPath)),
                ('paymentImage', models.ImageField(upload_to=ecommerce.models.getEcommerceBannerUploadPath)),
                ('paymentPortrait', models.ImageField(upload_to=ecommerce.models.getEcommerceBannerUploadPath)),
            ],
        ),
    ]
