# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0052_genericimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericimage',
            name='backgroundImage',
            field=models.ImageField(upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
        migrations.AlterField(
            model_name='genericimage',
            name='cartImage',
            field=models.ImageField(upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
        migrations.AlterField(
            model_name='genericimage',
            name='paymentImage',
            field=models.ImageField(upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
        migrations.AlterField(
            model_name='genericimage',
            name='paymentPortrait',
            field=models.ImageField(upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
    ]
