# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0053_auto_20180910_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericimage',
            name='searchBgImage',
            field=models.ImageField(null=True, upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
    ]
