# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0054_genericimage_searchbgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericimage',
            name='blogPageImage',
            field=models.ImageField(null=True, upload_to=ecommerce.models.getEcommerceCenericImageUploadPath),
        ),
    ]
