# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0056_auto_20180922_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
