# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0057_auto_20180922_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='filesPk',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
