# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0058_cart_prodsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prodVarPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
