# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0058_listing_filespk'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='imageIndex',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
