# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0059_media_imageindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['imageIndex']},
        ),
    ]
