# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0060_auto_20181009_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='filesPk',
        ),
    ]
