# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0061_remove_cart_prodvarprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prodVarPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
