# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0061_remove_listing_filespk'),
        ('ecommerce', '0062_cart_prodvarprice'),
    ]

    operations = [
    ]
