# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0063_merge_20181009_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericproduct',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
