# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0064_auto_20181022_1101'),
        ('ecommerce', '0064_genericproduct_restricted'),
    ]

    operations = [
    ]
