# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0065_merge_20181022_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='topLevelMenu',
            field=models.BooleanField(default=False),
        ),
    ]
