# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0066_pages_toplevelmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingCharges',
            field=models.IntegerField(default=0),
        ),
    ]
