# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0072_auto_20181116_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='body',
            field=models.CharField(max_length=50000),
        ),
    ]
