# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0074_cart_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
