# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0075_orderqtymap_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='productIndex',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
