# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0076_listing_productindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['productIndex']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='productIndex',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
