# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0078_merge_20181130_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
    ]
