# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0079_auto_20181130_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericimage',
            name='backgroundImage',
        ),
    ]
