# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0081_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.PositiveIntegerField(default=0)),
                ('sortname', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phonecode', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='ecommerce.Country')),
            ],
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
