# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0083_auto_20181228_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paidAmount',
            field=models.FloatField(default=0),
        ),
    ]
