# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0083_auto_20181218_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='ecommerce.States'),
        ),
    ]
