# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0084_auto_20181231_0554'),
        ('ecommerce', '0084_auto_20181230_1320'),
    ]

    operations = [
    ]
