# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0084_auto_20181218_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpincode',
            name='pin_id',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
