# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0085_merge_20181231_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countryCode',
            field=models.CharField(default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stateCode',
            field=models.CharField(default='KA', max_length=10),
        ),
    ]
