# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0085_merge_20181231_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='modeOfPayment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
