# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0085_genericpincode_pin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpincode',
            name='pin_id',
        ),
    ]
