# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0086_remove_genericpincode_pin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='orderBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
