# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0086_remove_genericpincode_pin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='flag',
            field=models.ImageField(null=True, upload_to=ecommerce.models.getEcommerceCountryUploadPath),
        ),
    ]
