# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0086_auto_20190102_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='priceDuringOrder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
