# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0087_orderqtymap_orderby'),
        ('ecommerce', '0087_countries_flag'),
    ]

    operations = [
    ]
