# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0086_orderqtymap_modeofpayment'),
        ('ecommerce', '0087_orderqtymap_priceduringorder'),
    ]

    operations = [
    ]
