# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0089_auto_20190108_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingCharges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalGst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='discountAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='gstAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='paidAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='priceDuringOrder',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='refundAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
