# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_auto_20180918_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='typ',
            field=models.CharField(choices=[('unit', 'unit'), ('cartan', 'cartan'), ('pieces', 'pieces'), ('packages', 'packages')], default='unit', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='gst',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='pan',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='statecode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
