# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_auto_20180921_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='statecode',
        ),
        migrations.AddField(
            model_name='service',
            name='gst',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pan',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='statecode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
