# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_remove_service_statecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commoditiescontact', to='warehouse.Contact'),
        ),
    ]
