# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_commodity_commodityfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commoditiescontact', to='warehouse.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='commodityFor',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='contact',
        ),
        migrations.AddField(
            model_name='commodity',
            name='customercommodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactcommodities', to='warehouse.CustomerCommodity'),
        ),
    ]
