# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_auto_20181005_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fromDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='toDate',
            field=models.DateTimeField(null=True),
        ),
    ]
