# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_auto_20181019_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='archivedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='toDate',
            field=models.DateField(null=True),
        ),
    ]
