# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_contract_activestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='totalTax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
