# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0036_invoice_totaltax'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='totalArea',
            field=models.FloatField(null=True),
        ),
    ]
