# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_space_totalarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='totalArea',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
