# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_auto_20181201_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='spaceGiven',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
