XXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX  FFFFFFF XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX FFFFFX XXXXXXXXXXXXX XXXXXXXXXXXXXX
       FFFFFFF

    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXX X XXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX
      XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX XXXX X XXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX
      XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXX X XXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           FFFFFFFFFFFFFFF
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXX
