# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.CharField(max_length=500, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('refurbished', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('returnComment', models.CharField(max_length=200, null=True)),
                ('approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('modelNo', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNos', models.CharField(max_length=500, null=True)),
                ('warrantyTill', models.DateField(null=True)),
                ('manufacturedOn', models.DateField(null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('poNumber', models.PositiveIntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='assets.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsCheckedIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
                ('sentTo', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsCheckedOut', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='allotment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsAlloted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotment', to=settings.AUTH_USER_MODEL),
        ),
    ]
