# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

import clientRelationships.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(choices=[('call', 'call'), ('meeting', 'meeting'), ('mail', 'mail'), ('todo', 'todo'), ('note', 'note'), ('stateChange', 'stateChange')], default='call', max_length=11)),
                ('data', models.CharField(max_length=300)),
                ('notes', models.TextField(max_length=1000, null=True)),
                ('doc', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipActivity)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('emailSecondary', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('mobileSecondary', models.CharField(max_length=12, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('notes', models.TextField(max_length=300, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('dp', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContactDP)),
                ('male', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ERP.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('quoted', 'quoted'), ('approved', 'approved'), ('billed', 'billed'), ('received', 'received'), ('dueElapsed', 'dueElapsed')], default='quoted', max_length=10)),
                ('dueDate', models.DateField(null=True)),
                ('details', models.TextField(max_length=10000, null=True)),
                ('data', models.CharField(max_length=10000, null=True)),
                ('billedDate', models.DateTimeField(null=True)),
                ('recievedDate', models.DateTimeField(null=True)),
                ('archivedDate', models.DateTimeField(null=True)),
                ('approvedDate', models.DateTimeField(null=True)),
                ('grandTotal', models.PositiveIntegerField(default=0)),
                ('totalTax', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(default=0, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=4)),
                ('state', models.CharField(choices=[('created', 'created'), ('contacted', 'contacted'), ('demo', 'demo'), ('requirements', 'requirements'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('conclusion', 'conclusion')], default='created', max_length=13)),
                ('requirements', models.TextField(max_length=10000, null=True)),
                ('probability', models.SmallIntegerField(default=100)),
                ('closeDate', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('na', 'na'), ('won', 'won'), ('lost', 'lost')], default='na', max_length=4)),
                ('doc', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContract)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('duePenalty', models.PositiveIntegerField(default=0, null=True)),
                ('duePeriod', models.PositiveIntegerField(default=7)),
                ('billingType', models.CharField(choices=[('fixed', 'fixed'), ('monthly', 'monthly'), ('hourly', 'hourly')], max_length=7, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='ERP.service')),
                ('contacts', models.ManyToManyField(blank=True, related_name='deals', to='clientRelationships.Contact')),
                ('internalUsers', models.ManyToManyField(blank=True, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealsCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('typ', models.CharField(choices=[('HSN', 'HSN'), ('SAC', 'SAC')], default='HSN', max_length=5)),
                ('code', models.PositiveIntegerField()),
                ('taxRate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slot', models.CharField(choices=[('N/A', 'N/A'), ('1 AM', '1 AM'), ('2 AM', '2 AM'), ('3 AM', '3 AM'), ('4 AM', '4 AM'), ('5 AM', '5 AM'), ('6 AM', '6 AM'), ('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 AM', '12 AM'), ('13 PM', '13 PM'), ('14 PM', '14 PM'), ('15 PM', '15 PM'), ('16 PM', '16 PM'), ('17 PM', '17 PM'), ('18 PM', '18 PM'), ('19 PM', '19 PM'), ('20 PM', '20 PM'), ('21 PM', '21 PM'), ('22 PM', '22 PM'), ('23 PM', '23 PM'), ('24 PM', '24 PM')], default='N/A', max_length=11)),
                ('email', models.TextField(blank=True, max_length=500, null=True)),
                ('typ', models.TextField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='scheduleUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clientRelationships.Deal'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientRelationships.Deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='internalUsers',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
