# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0005_merge_20180615_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='billingType',
            field=models.CharField(choices=[('fixed', 'fixed'), ('monthly', 'monthly'), ('hourly', 'hourly')], max_length=7, null=True),
        ),
    ]
