# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0006_deal_billingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='totalTax',
            field=models.FloatField(default=0),
        ),
    ]
