# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='primaryApprover',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='reportingTo',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='secondaryApprover',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approvedBy',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='user',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='payroll',
        ),
        migrations.DeleteModel(
            name='rank',
        ),
    ]
