# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_leave_created'),
    ]

    operations = [

    ]
