# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:08
from __future__ import unicode_literals

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_auto_20180711_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayPicture',
            field=models.ImageField(null=True, upload_to=HR.models.getDisplayPicturePath),
        ),
    ]
