# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_auto_20180711_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='esic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pfAccNo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pfAmnt',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pfUniNo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
