# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_service_contactperson'),
        ('HR', '0013_auto_20180820_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('text', models.ManyToManyField(blank=True, related_name='roles', to='ERP.application')),
            ],
        ),
    ]
