# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_auto_20181015_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empType',
            field=models.CharField(choices=[(b'full time', b'full time'), (b'part time', b'part time')], default=b'full time', max_length=4),
        ),
    ]
