# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_profile_emptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='accounted',
            field=models.BooleanField(default=False),
        ),
    ]
