# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='user',
        ),
        migrations.DeleteModel(
            name='payroll',
        ),
    ]
