# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0015_auto_20180709_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
