# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0016_auto_20180904_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=12, null=True)),
                ('incoming', models.BooleanField(default=False)),
                ('frmOrTo', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lat', models.CharField(max_length=12, null=True)),
                ('lon', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('frm', models.CharField(max_length=12, null=True)),
                ('to', models.CharField(max_length=12, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('spam', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
