# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0020_mobilecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='incoming',
        ),
        migrations.AddField(
            model_name='call',
            name='typ',
            field=models.CharField(choices=[(b'INCOMING', b'INCOMING'), (b'OUTGOING', b'OUTGOING'), (b'MISSED', b'MISSED')], default=b'INCOMING', max_length=100),
        ),
    ]
