# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0021_auto_20180927_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sms',
            unique_together=set([('body', 'frm')]),
        ),
    ]
