# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0022_auto_20180927_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='owner',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='body',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
