# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0023_auto_20180927_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mobilecontact',
            name='owner',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='dated',
            field=models.DateTimeField(),
        ),
    ]
