# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0025_auto_20181005_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gmailAge',
            field=models.DateTimeField(null=True),
        ),
    ]
