# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0028_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment',
            field=models.FileField(upload_to=b''),
        ),
    ]
