# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:33
from __future__ import unicode_literals

import HR.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0029_auto_20181008_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accNumber', models.CharField(max_length=100, null=True)),
                ('bankName', models.CharField(max_length=300, null=True)),
                ('typ', models.CharField(max_length=20, null=True)),
                ('ifscCode', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userBankAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(upload_to=b'')),
                ('bankAct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountBalanceSheets', to='HR.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dat', models.DateField(max_length=20, null=True)),
                ('description', models.DateField(max_length=500, null=True)),
                ('firstLCat', models.DateField(max_length=100, null=True)),
                ('secondLCat', models.DateField(max_length=100, null=True)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('bankstatement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankStatements', to='HR.BankStatement')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.CharField(choices=[(b'na', b'na'), (b'shopping', b'shopping'), (b'bill', b'bill'), (b'bank update', b'bank update'), (b'others', b'others'), (b'credit', b'credit'), (b'debit', b'debit')], default=b'na', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment',
            field=models.FileField(upload_to=HR.models.getBankStatementPath),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([('accNumber', 'bankName')]),
        ),
    ]
