# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:04
from __future__ import unicode_literals

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0030_auto_20181023_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='attachment',
            field=models.FileField(upload_to=HR.models.getBankStatementPath),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment',
            field=models.FileField(upload_to=HR.models.getEmailAttachmentPath),
        ),
    ]
