# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0032_auto_20181023_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='credit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='debit',
            field=models.FloatField(default=0, null=True),
        ),
    ]
