# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0036_remove_settingtypes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='typ',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
