# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0037_sms_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.CharField(choices=[(b'na', b'na'), (b'shopping', b'shopping'), (b'bill', b'bill'), (b'bank update', b'bank update'), (b'others', b'others'), (b'credit', b'credit'), (b'debit', b'debit'), (b'SPAM', b'SPAM'), (b'SOCIAL', b'SOCIAL')], default=b'na', max_length=20, null=True),
        ),
    ]
