# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0040_auto_20181128_0606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='bankAct',
        ),
        migrations.RemoveField(
            model_name='call',
            name='user',
        ),
        migrations.RemoveField(
            model_name='email',
            name='files',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mobilecontact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='bankstatement',
        ),
        migrations.DeleteModel(
            name='SettingTypes',
        ),
        migrations.AlterUniqueTogether(
            name='sms',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sms',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='BankStatement',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MobileContact',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
