# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 05:41
from __future__ import unicode_literals

import PIM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contentFK',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ogimage',
            field=models.ImageField(null=True, upload_to=PIM.models.getOGImageAttachment),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ogimageUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagsCSV',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='contentType',
            field=models.CharField(choices=[(b'article', b'article'), (b'tutorial', b'tutorial'), (b'whitepaper', b'whitepaper'), (b'product', b'product'), (b'book', b'book'), (b'question', b'question')], default=b'article', max_length=15),
        ),
    ]
