# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0006_auto_20180401_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='source',
            field=models.TextField(max_length=200000, null=True),
        ),
    ]
