# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0008_blogpost_contentfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='calendar',
        ),
    ]
