# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0055_genericimage_blogpageimage'),
        ('PIM', '0008_auto_20180918_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='suggestedProducts',
            field=models.ManyToManyField(blank=True, related_name='blogSuggetProducts', to='ecommerce.listing'),
        ),
    ]
