# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0010_auto_20181031_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='calendarEntries', to='PIM.Contact'),
        ),
    ]
