# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0011_auto_20190126_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contentType',
            field=models.CharField(choices=[(b'article', b'article'), (b'tutorial', b'tutorial'), (b'whitepaper', b'whitepaper'), (b'product', b'product'), (b'book', b'book'), (b'question', b'question'), (b'course', b'course'), (b'paperGroup', b'paperGroup')], default=b'article', max_length=15),
        ),
    ]
