# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0011_calendar_clients'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='calendar',
        #     name='clients',
        # ),
    ]
