# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0012_remove_calendar_clients'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='calendar',
        #     name='clients',
        #     field=models.ManyToManyField(blank=True, related_name='calendarEntries', to='PIM.Contact'),
        # ),
    ]
