# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('filterFrom', models.DateField(blank=True, null=True)),
                ('filterTo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('closed', 'closed')], default='created', max_length=15)),
                ('typ', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('call', 'call')], max_length=10, null=True)),
                ('msgBody', models.CharField(blank=True, max_length=1000, null=True)),
                ('emailSubject', models.CharField(blank=True, max_length=1000, null=True)),
                ('emailBody', models.CharField(blank=True, max_length=10000, null=True)),
                ('directions', models.CharField(blank=True, max_length=10000, null=True)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followupDate', models.DateTimeField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
                ('typ', models.CharField(choices=[('inbound', 'inbound'), ('outbound', 'smoutbounds'), ('emailSent', 'emailSent'), ('emailRecieved', 'emailRecieved'), ('smsSent', 'smsSent'), ('smsRecieved', 'smsRecieved'), ('task', 'task'), ('comment', 'comment'), ('closed', 'closed'), ('converted', 'converted')], max_length=20, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CampaignLogs', to='marketing.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('referenceId', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('pinCode', models.CharField(max_length=10, null=True)),
                ('subscribe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254)),
                ('requirements', models.CharField(max_length=500, null=True)),
                ('jobLevel', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('companyCategory', models.CharField(max_length=50, null=True)),
                ('companyExpertise', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('mobileNumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dated', models.DateField()),
                ('slot', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Created', max_length=15, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduleOrganizer', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='scheduleParticipants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='tags',
            field=models.ManyToManyField(to='marketing.Tag'),
        ),
        migrations.AddField(
            model_name='campaignlogs',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CampaignLogs', to='marketing.Contacts'),
        ),
        migrations.AddField(
            model_name='campaignlogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CampaignLogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(to='marketing.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together=set([('email', 'source')]),
        ),
    ]
