# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_auto_20181208_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254)),
                ('requirements', models.CharField(max_length=500, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
