# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_auto_20181208_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='role',
            new_name='company',
        ),
        migrations.AddField(
            model_name='leads',
            name='companyCategory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='companyExpertise',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='jobLevel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='mobileNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
