# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0018_auto_20181208_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduleOrganizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='scheduleParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
