# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_auto_20181211_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='Created', max_length=15, null=True),
        ),
    ]
