# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='sourceFrom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
