# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_contacts_sourcefrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='sourceFrom',
        ),
    ]
