# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_contacts_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together=set([('email', 'source')]),
        ),
    ]
