# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('saved', 'saved'), ('submitted', 'submitted'), ('approved', 'approved')], default='created', max_length=10, null=True)),
                ('checkIn', models.DateTimeField(null=True)),
                ('checkOut', models.DateTimeField(null=True)),
                ('totaltime', models.CharField(max_length=30, null=True)),
                ('approvedBy', models.ManyToManyField(blank=True, related_name='times', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeSheetCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('approvalComment', models.CharField(max_length=10000, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.TimeSheet')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsTime', to='projects.project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set([('user', 'date')]),
        ),
    ]
