# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20180530_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='totaltime',
            field=models.FloatField(null=True),
        ),
    ]
