# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_timesheet_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='totaltime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
