# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_auto_20181116_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='totaltime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
