# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_auto_20181116_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='totaltime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
