# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('attachment', models.FileField(null=True, upload_to=support.models.getSupportChatAttachment)),
                ('message', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('sentByAgent', models.BooleanField(default=False)),
            ],
        ),
    ]
