# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('part_no', models.CharField(max_length=20, null=True, unique=True)),
                ('description_1', models.CharField(max_length=100, null=True)),
                ('description_2', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('customs_no', models.CharField(max_length=15, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentProduct', to='support.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.FileField(null=True, upload_to=support.models.getUploadedProductSheets)),
                ('file_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsSheet', to='support.ProductSheet'),
        ),
    ]
