# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportchatfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportchatfile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='supportchatfile',
            name='message',
        ),
    ]
