# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20180922_0953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_auto_20181128_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('responsible', models.ManyToManyField(blank=True, related_name='managingService', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='ERP.service')),
            ],
        ),
    ]
