# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
