# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20180806_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportMessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='supportchatfile',
            name='sentByAgent',
        ),
        migrations.AddField(
            model_name='supportchatfile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportFile', to=settings.AUTH_USER_MODEL),
        ),
    ]
