# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_auto_20181129_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='support.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersBoM', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
