# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20180807_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='attachmentType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
