# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='products',
        ),
        migrations.AddField(
            model_name='bom',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Products'),
        ),
    ]
