# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20181203_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='project',
            field=models.ManyToManyField(to='support.Projects'),
        ),
    ]
