# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_bom_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='project',
        ),
        migrations.AddField(
            model_name='bom',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Projects'),
        ),
    ]
