# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20181204_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='project',
        ),
        migrations.AddField(
            model_name='bom',
            name='project',
            field=models.ManyToManyField(to='support.Projects'),
        ),
    ]
