# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0009_auto_20181204_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='quantity1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='quantity2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved1_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved1_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approveduser1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved2_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='approved2_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approveduser2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent_for_approval', 'sent_for_approval'), ('reconciled', 'reconciled'), ('approved', 'approved')], default='created', max_length=10),
        ),
    ]
