# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20181205_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
