# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_customerprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportchat',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
