# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_projects_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='price',
        ),
        migrations.AddField(
            model_name='bom',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
