# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_auto_20180810_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='supportBubbleColor',
            field=models.CharField(default='#286EFA', max_length=20, null=True),
        ),
    ]
