# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0012_customerprofile_supportbubblecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('reviewed', 'reviewed'), ('resolved', 'resolved'), ('archived', 'archived'), ('escalatedL1', 'escalatedL1'), ('escalatedL2', 'escalatedL2')], default='started', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
