# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20181205_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='approved1_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='approved2_date',
            field=models.DateField(null=True),
        ),
    ]
