# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_chatthread_reviewcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
