# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='products',
            new_name='product',
        ),
    ]
