# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_auto_20181206_0832'),
        ('support', '0014_auto_20181206_0601'),
    ]

    operations = [
    ]
