# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
