# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_merge_20181206_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='comm_nr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='machinemodel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
