# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_visitor_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='chatedDate',
            field=models.DateField(null=True),
        ),
    ]
