# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_auto_20181206_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='customer_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
