# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20180812_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='CustomerFeedback',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='customerRating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
