# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_bom_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
