# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_projects_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='revision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
