# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_auto_20181207_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bar_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
