# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_auto_20180813_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='windowColor',
            field=models.CharField(default='#000000', max_length=20, null=True),
        ),
    ]
