# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_auto_20180814_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=20000, null=True)),
                ('docs', models.FileField(blank=True, null=True, upload_to=support.models.getCustomerAttachments)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerDocumentatios', to='support.CustomerProfile')),
            ],
        ),
    ]
