# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
