# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_delete_chatthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('reviewed', 'reviewed'), ('resolved', 'resolved'), ('archived', 'archived'), ('escalatedL1', 'escalatedL1'), ('escalatedL2', 'escalatedL2')], default='started', max_length=15)),
                ('customerRating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customerFeedback', models.CharField(max_length=3000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatThread', to='support.CustomerProfile')),
            ],
        ),
    ]
