# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_documentation'),
        ('support', '0022_chatthread'),
    ]

    operations = [
    ]
