# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_invoicemain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qty', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.FloatField(null=True)),
                ('stock', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Products')),
            ],
        ),
        migrations.RenameModel(
            old_name='InvoiceMain',
            new_name='MaterialIssueMain',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='materialissuemain',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='materialissuemain',
            name='materialIsuue',
            field=models.ManyToManyField(related_name='invoiceqty', to='support.MaterialIssue'),
        ),
    ]
