# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0024_auto_20181210_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissuemain',
            name='materialIsuue',
            field=models.ManyToManyField(related_name='materialqty', to='support.MaterialIssue'),
        ),
        migrations.AlterField(
            model_name='materialissuemain',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialproject', to='support.Projects'),
        ),
        migrations.AlterField(
            model_name='materialissuemain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
