# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_auto_20181210_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialissuemain',
            old_name='materialIsuue',
            new_name='materialIssue',
        ),
    ]
