# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0025_auto_20180821_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatAgentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
