# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0026_auto_20181210_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='savedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
