# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_auto_20180823_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='userDevice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='userDeviceIp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='userApiKey',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
