# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0028_auto_20180824_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='userDevice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='userDeviceIp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
