# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0028_auto_20181212_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='assessableValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='clearingCharges1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='clearingCharges2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='freight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='gst1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='gst2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='insurance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='invoiceValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='packing',
            field=models.FloatField(null=True),
        ),
    ]
