# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0029_auto_20180824_0843'),
        ('support', '0028_auto_20180824_0835'),
    ]

    operations = [
    ]
