# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0030_merge_20180827_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='userDevice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='userDeviceIp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='userApiKey',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
