# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0030_auto_20181213_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='packingVal',
            new_name='packing',
        ),
    ]
