# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0031_auto_20181213_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='customer_price',
            new_name='landed_price',
        ),
    ]
