# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0032_customerprofile_firstmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='chatDuration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='firstResponseTime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
