# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_auto_20180829_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='responseTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
