# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_bom_invoice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='customer_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
