# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0034_bom_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prodQty',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
