# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0034_supportchat_responsetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='avgResponseTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
