# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0036_remove_chatthread_avgresponsetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='firstResponseTime',
        ),
    ]
