# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_remove_chatthread_firstresponsetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='firstResponseTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
