# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_stockcheck_stockchecklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockchecklog',
            name='count',
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
