# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0038_auto_20181215_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheck',
            name='status',
            field=models.CharField(choices=[('live', 'live'), ('completed', 'completed')], default='live', max_length=10),
        ),
    ]
