# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0039_stockcheck_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcheck',
            old_name='product',
            new_name='inventory',
        ),
    ]
