# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0040_documentversion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='articleOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
