# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0041_documentation_articleowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
