# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0042_documentation_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='support.CompanyProcess'),
        ),
    ]
