# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0042_auto_20181218_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='support.Vendor'),
        ),
    ]
