# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0043_documentation_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
