# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0043_projects_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='exRate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent_for_approval', 'sent_for_approval'), ('reconciled', 'reconciled'), ('approved', 'approved'), ('archieve', 'archieve')], default='created', max_length=10),
        ),
    ]
