# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0044_cannedresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='iconColor',
            field=models.CharField(default='#FFFFFF', max_length=20, null=True),
        ),
    ]
