# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0044_auto_20181220_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent_for_approval', 'sent_for_approval'), ('approved', 'approved'), ('grn', 'grn'), ('archieve', 'archieve')], default='created', max_length=10),
        ),
    ]
