# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_service_contactperson'),
        ('support', '0045_customerprofile_iconcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedresponses',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cannedResponses', to='ERP.service'),
        ),
    ]
