# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0045_auto_20181220_1006'),
        ('support', '0044_auto_20181220_1108'),
    ]

    operations = [
    ]
