# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0046_merge_20181220_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='exRate',
            field=models.FloatField(default=75),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent_for_approval', 'sent_for_approval'), ('approved', 'approved'), ('ongoing', 'ongoing'), ('archieve', 'archieve')], default='created', max_length=10),
        ),
    ]
