# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0047_auto_20181220_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assessableValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='clearingCharges1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='clearingCharges2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='freight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='gst1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='gst2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='insurance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='packing',
            field=models.FloatField(default=0),
        ),
    ]
