# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0047_documentversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='userDeviceIp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
