# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0048_auto_20180904_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='userDevice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='userDeviceIp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
