# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0049_auto_20181220_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='revision',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
