# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0049_auto_20180904_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='typ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
