# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0049_projects_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profit',
            field=models.FloatField(default=10),
        ),
    ]
