# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0050_auto_20181220_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='poNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
