# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0050_chatthread_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='agent_capture',
            field=models.FileField(blank=True, null=True, upload_to=support.models.getSupportChatAttachment),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='visitor_capture',
            field=models.FileField(blank=True, null=True, upload_to=support.models.getSupportChatAttachment),
        ),
    ]
