# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0051_auto_20181221_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profitMargin',
            field=models.FloatField(default=5),
        ),
    ]
