# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0051_auto_20181024_0416'),
        ('support', '0051_auto_20181024_0551'),
    ]

    operations = [
    ]
