# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0052_auto_20181221_0749'),
        ('support', '0051_projects_ponumber'),
    ]

    operations = [
    ]
