# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0053_auto_20181030_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='archivedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='archivedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='closedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='closedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='escalatedL1By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalatedL1User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='escalatedL1On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='escalatedL2By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalatedL2User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='escalatedL2On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='resolvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolvedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='resolvedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
