# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0054_auto_20181224_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='quoteRefNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
