# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0055_projects_quoterefnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='delivery',
            field=models.CharField(default='6 weeks from the date of receipt of PO and advance', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='paymentTerms',
            field=models.CharField(default='100% advance along with order', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='quoteValidity',
            field=models.CharField(default='30 days from quote date', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='terms',
            field=models.CharField(default='EX-WORKS, BRUDERER AG, Switzerland', max_length=200),
        ),
    ]
