# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0055_auto_20181030_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='resolvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolvedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='resolvedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
