# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0056_auto_20181224_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='custom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='gst',
            field=models.FloatField(default=0),
        ),
    ]
