# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0056_auto_20181030_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='logs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
