# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0058_heartbeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='user',
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Heartbeat',
        ),
    ]
