# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0059_auto_20181226_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customs_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='part_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
