# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0059_auto_20181205_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
