# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0060_auto_20181227_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='custom',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='gst',
            field=models.FloatField(default=0, null=True),
        ),
    ]
