# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0061_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
