# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0062_heartbeat_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
