# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0063_auto_20181227_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='customs_no',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
