# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0063_auto_20181206_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='day_duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
