# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0064_bom_customs_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='personName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
