# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0064_heartbeat_day_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='videoAndAudio',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
