# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0065_vendor_personname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='customer_ref',
        ),
        migrations.AddField(
            model_name='projects',
            name='enquiry_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='quote_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
