# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0066_auto_20181229_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStockSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=0, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockSummaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dated', models.DateField(null=True)),
                ('stockValue', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectstocksummary',
            name='stockReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectStockReport', to='support.StockSummaryReport'),
        ),
    ]
