# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0067_auto_20190102_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummaryreport',
            name='dated',
            field=models.DateField(null=True, unique=True),
        ),
    ]
