# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0067_auto_20190106_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='chatIconType',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
