# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0068_auto_20190102_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='replaced',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
