# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0068_auto_20190106_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('closed', 'closed'), ('reviewed', 'reviewed'), ('resolved', 'resolved'), ('archived', 'archived'), ('escalatedL1', 'escalatedL1'), ('escalatedL2', 'escalatedL2'), ('late', 'late')], default='started', max_length=15),
        ),
    ]
