# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0069_products_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='responsible',
            field=models.ManyToManyField(blank=True, null=True, related_name='managingService', to=settings.AUTH_USER_MODEL),
        ),
    ]
