# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0069_auto_20190111_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='isLate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='lastActivity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
