# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0070_auto_20190117_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='location',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('closed', 'closed'), ('reviewed', 'reviewed'), ('resolved', 'resolved'), ('archived', 'archived'), ('escalatedL1', 'escalatedL1'), ('escalatedL2', 'escalatedL2'), ('missed', 'missed')], default='started', max_length=15),
        ),
    ]
