# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0071_auto_20190125_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='mailSent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
