# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0072_projects_junkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='poDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='quoteDate',
            field=models.DateField(null=True),
        ),
    ]
