# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0073_auto_20190106_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='shipmentDetails',
            field=models.CharField(default='Freight forwarder -', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='shipmentMode',
            field=models.CharField(default='Road', max_length=200),
        ),
    ]
