# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0073_auto_20190127_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
