# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0074_auto_20190106_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='totweight',
            field=models.FloatField(default=0),
        ),
    ]
