# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0074_auto_20190129_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_blink',
            field=models.BooleanField(default=False),
        ),
    ]
