# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0075_projects_totweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='totweight',
            new_name='weightValue',
        ),
    ]
