# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0076_auto_20190106_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='paymentTerms1',
            field=models.CharField(default='100% advance along with order', max_length=200),
        ),
    ]
