# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0009_auto_20190116_1214'),
        ('support', '0076_supportchat_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('field_typ', models.CharField(choices=[('typeahead', 'typeahead'), ('text', 'text'), ('dropdown', 'dropdown')], default='typeahead', max_length=15)),
                ('parameters', models.CharField(max_length=100, null=True)),
                ('field_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('form_name', models.CharField(max_length=50, null=True)),
                ('function_name', models.CharField(max_length=50, null=True)),
                ('form_description', models.CharField(max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamicFormCompany', to='ERP.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamicFormUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamicField', to='support.DynamicForm'),
        ),
    ]
