# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0077_auto_20190130_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
