# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0078_auto_20190131_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='support_icon',
            field=models.ImageField(null=True, upload_to=support.models.getdpPath),
        ),
    ]
