# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0078_inventory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='addedqty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
