# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0079_inventory_addedqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='project',
        ),
        migrations.AddField(
            model_name='bom',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Projects'),
        ),
    ]
