# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0079_customerprofile_support_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=50)),
                ('timeDuration', models.FloatField(default=0.0)),
            ],
        ),
    ]
