# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0080_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='typ',
            field=models.CharField(choices=[('dataCollection', 'dataCollection'), ('rpc', 'rpc'), ('restCall', 'restCall')], default='restCall', max_length=15),
        ),
    ]
