# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0082_materialissuemain_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialissuemain',
            name='service',
        ),
        migrations.AddField(
            model_name='materialissuemain',
            name='vandor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vandormaterial', to='support.Vendor'),
        ),
    ]
