# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0084_auto_20190116_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='currency',
            field=models.CharField(choices=[('CHF', 'CHF'), ('INR', 'INR'), ('EUR', 'EUR'), ('USD', 'USD'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('ZAR', 'ZAR')], default='CHF', max_length=10),
        ),
    ]
