# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0085_projects_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='termspo',
            field=models.CharField(default='EX-WORKS, BRUDERER AG, Switzerland', max_length=200),
        ),
    ]
