# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0086_projects_termspo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='grnDate',
            field=models.DateField(null=True),
        ),
    ]
