# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0089_invoice_invoiceqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceqty',
            name='project',
        ),
    ]
