# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0089_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_no', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('taxableprice', models.FloatField(default=0, null=True)),
                ('cgst', models.FloatField(default=0, null=True)),
                ('cgstVal', models.FloatField(default=0, null=True)),
                ('sgst', models.FloatField(default=0, null=True)),
                ('sgstVal', models.FloatField(default=0, null=True)),
                ('igst', models.FloatField(default=0, null=True)),
                ('igstVal', models.FloatField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Products')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Projects')),
            ],
        ),
    ]
