# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20181224_0806'),
        ('support', '0089_invoice_invoiceqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('challanNo', models.CharField(blank=True, max_length=20, null=True)),
                ('challanDate', models.DateField(null=True)),
                ('deliveryThr', models.CharField(blank=True, max_length=50, null=True)),
                ('refNo', models.CharField(blank=True, max_length=50, null=True)),
                ('apprx', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ERP.service')),
                ('materialIssue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.MaterialIssue')),
            ],
        ),
        migrations.RemoveField(
            model_name='materialissuemain',
            name='vendor',
        ),
    ]
