# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0090_auto_20190125_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='materialIssue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.MaterialIssueMain'),
        ),
    ]
