# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0090_remove_invoiceqty_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceqty',
            name='description_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceqty',
            name='part_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
