# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0091_auto_20190125_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallan',
            name='customer',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customeraddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customergst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='customername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
