# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0091_auto_20190119_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceqty',
            name='qty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
