# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0093_stockcheckitem_stockcheckreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheckitem',
            name='stockReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockreportDetails', to='support.StockCheckReport'),
        ),
    ]
