# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dated', models.DateField()),
                ('slot', models.CharField(max_length=15)),
                ('emailId', models.CharField(max_length=20)),
            ],
        ),
    ]
