# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180325_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
