# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0068_storeqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storeQty',
            field=models.ManyToManyField(blank=True, related_name='productStore', to='POS.StoreQty'),
        ),
    ]
