# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0069_product_storeqty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Pincode',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
    ]
