# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0070_auto_20180823_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posStsore', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
