# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0072_remove_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
    ]
