# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0073_auto_20180830_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
