# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0075_product_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='howMuch',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productverient',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
