# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0077_auto_20181005_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productverient',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
