# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0078_auto_20181008_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='productverient',
            name='discountedPrice',
            field=models.FloatField(null=True),
        ),
    ]
