# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0080_auto_20181010_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productverient',
            name='discountedPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
