# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0081_auto_20181010_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storeQty',
        ),
        migrations.AddField(
            model_name='storeqty',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeqty',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeProducts', to='POS.Product'),
        ),
        migrations.AddField(
            model_name='storeqty',
            name='productVariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeProdVar', to='POS.ProductVerient'),
        ),
    ]
