# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0082_auto_20181012_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeqty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeProducts', to='POS.Product'),
        ),
        migrations.AlterField(
            model_name='storeqty',
            name='productVariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeProdVar', to='POS.ProductVerient'),
        ),
    ]
