# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0083_auto_20181012_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeqty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeProduct', to='POS.Product'),
        ),
    ]
