# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0085_auto_20181012_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeqty',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POSStoreDetail', to='POS.Store'),
        ),
    ]
