# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0086_auto_20181013_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeqty',
            unique_together=set([('store', 'product', 'master')]),
        ),
    ]
