# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0090_auto_20181015_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='productverient',
            name='serialId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
