# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0091_productverient_serialid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grossWeight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
