# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0093_auto_20181031_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productverient',
            name='unitPerpack',
            field=models.FloatField(default=0),
        ),
    ]
