# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0094_auto_20181113_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeqty',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
