# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0097_auto_20181128_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='productverient',
            name='prodDesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
