# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0097_auto_20181128_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturemanifest',
            name='specialInstruction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
