# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0098_auto_20181128_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturemanifest',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Started', 'Started'), ('Completed', 'Completed')], default='Created', max_length=10, null=True),
        ),
    ]
