# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0098_productverient_proddesc'),
        ('POS', '0099_auto_20181128_0825'),
    ]

    operations = [
    ]
