# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0102_product_productmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='modeOfPayment',
            field=models.CharField(choices=[('card', 'card'), ('netBanking', 'netBanking'), ('cash', 'cash'), ('cheque', 'cheque'), ('wallet', 'wallet'), ('cashOnDelivery', 'cashOnDelivery')], max_length=10, null=True),
        ),
    ]
