# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0103_auto_20181218_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Created', max_length=20, null=True),
        ),
    ]
