# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0104_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productMeta',
        ),
    ]
