# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0106_product_productmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='barCVal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orderBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordereDeliveredUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
