# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 08:35
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0032_auto_20180427_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCourseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrenceBook', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='LMS.Book')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='LMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('comment', 'comment'), ('like', 'like')], max_length=50, null=True)),
                ('description', models.CharField(max_length=20000)),
                ('urlSuffix', models.CharField(choices=[('comment', 'comment'), ('like', 'like')], max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getChannelDPPath)),
            ],
        ),
        migrations.CreateModel(
            name='NotesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=2000, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getQAttachmentPath)),
                ('mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='LMS.Note')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='LMS.Course'),
        ),
    ]
