# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0033_auto_20190115_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcoursemap',
            old_name='refrenceBook',
            new_name='referenceBook',
        ),
    ]
