# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0034_auto_20190115_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcoursemap',
            unique_together=set([('book', 'course')]),
        ),
    ]
