# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 05:42
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0035_auto_20190115_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(null=True, upload_to=LMS.models.getNoteImagePath),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='urlSuffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
