# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0036_auto_20190116_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notessection',
            name='txt',
            field=models.TextField(null=True),
        ),
    ]
