# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0039_auto_20190116_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcer',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='paper',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
