# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0042_auto_20190117_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='paperDueDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
