# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0043_auto_20190117_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='paper',
        ),
    ]
