# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0044_remove_announcement_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
