# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0045_auto_20190118_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='LMS.Paper'),
        ),
    ]
