# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0046_announcement_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='notification',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('sms&email', 'sms&email')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='typ',
            field=models.CharField(choices=[('general', 'general'), ('quiz', 'quiz'), ('onlineclass', 'onlineclasss'), ('class', 'class'), ('offlinequiz', 'offlinequiz')], max_length=10, null=True),
        ),
    ]
