# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0047_auto_20190118_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
