# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 08:30
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0048_auto_20190118_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(null=True, upload_to=LMS.models.getHomeworkPath)),
                ('comment', models.TextField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworkcourse', to='LMS.Course')),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworkPaper', to='LMS.Paper')),
            ],
        ),
        migrations.AlterField(
            model_name='notessection',
            name='image',
            field=models.FileField(null=True, upload_to=LMS.models.getNoteSectionPath),
        ),
    ]
