# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0049_auto_20190118_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='comment',
            new_name='commment',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='course',
            new_name='hcourse',
        ),
    ]
