# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0050_auto_20190118_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='pdf',
            new_name='pdff',
        ),
    ]
