# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0051_auto_20190118_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='commment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='hcourse',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='pdff',
            new_name='pdf',
        ),
    ]
