# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0053_auto_20190118_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworkCourse', to='LMS.Course'),
        ),
    ]
