# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0054_auto_20190118_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='comments',
            new_name='comment',
        ),
    ]
