# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0055_auto_20190118_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
