# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0056_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='paperDueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
