# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0059_auto_20190118_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
