# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0060_auto_20190118_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
