# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-26 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0061_section_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('title', 'level')]),
        ),
    ]
