# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0062_auto_20190126_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='timelimit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
