# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0062_auto_20190126_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seoTitle',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
