# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0064_qpart_sequence'),
        ('LMS', '0063_paper_timelimit'),
    ]

    operations = [
    ]
