# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0065_merge_20190127_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='seoTitle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='LMS.Topic'),
        ),
    ]
