# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0066_auto_20190127_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notessection',
            name='note',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NotesSection',
        ),
    ]
