# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 05:55
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0067_auto_20190128_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('urlSuffix', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getNoteImagePath)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseNote', to='LMS.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='LMS.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='NotesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getNoteSectionPath)),
                ('mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='LMS.Note')),
            ],
        ),
    ]
