# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0068_note_notessection'),
        ('LMS', '0065_merge_20190127_1127'),
    ]

    operations = [
    ]
