# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0068_note_notessection'),
    ]

    operations = [
        migrations.AddField(
            model_name='notessection',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
