# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0069_merge_20190128_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marksObtained',
            field=models.FloatField(default=0),
        ),
    ]
