# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0071_papergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papergroup', to='LMS.PaperGroup'),
        ),
    ]
