# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0071_merge_20190129_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpart',
            options={'ordering': ['sequence']},
        ),
    ]
