# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0073_remove_papergroup_url'),
        ('LMS', '0072_auto_20190129_0552'),
    ]

    operations = [
    ]
