# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0075_auto_20190129_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperattempthistory',
            name='mark',
            field=models.FloatField(default=0),
        ),
    ]
