# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0076_auto_20190130_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperattempthistory',
            name='attempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperattempthistory',
            name='correctanswers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperattempthistory',
            name='incorrectanswers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperattempthistory',
            name='notattempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperattempthistory',
            name='notview',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperattempthistory',
            name='reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
