# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0076_auto_20190130_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='urlSuffix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
