# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0077_auto_20190130_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperattempthistory',
            name='correctanswers',
        ),
        migrations.RemoveField(
            model_name='paperattempthistory',
            name='incorrectanswers',
        ),
    ]
