# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0077_course_urlsuffix'),
        ('LMS', '0078_auto_20190130_0827'),
    ]

    operations = [
    ]
