# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0079_merge_20190131_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.TextField(null=True),
        ),
    ]
