# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0080_subject_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='topic',
            name='syllabus',
            field=models.TextField(null=True),
        ),
    ]
