# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0081_auto_20190202_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperattempthistory',
            name='sessionTime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
