# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 12:05
from __future__ import unicode_literals

import LMS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0083_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('page', models.CharField(max_length=100, null=True)),
                ('txt', models.TextField(null=True)),
                ('attachment', models.FileField(null=True, upload_to=LMS.models.getForumAttachmentPath)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forumthread', to='LMS.ForumThread'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
