# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0084_auto_20190204_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='page',
            new_name='parent',
        ),
    ]
