# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0085_auto_20190205_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='seoTitle',
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
