# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-07 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0086_forumcomment_verified'),
        ('LMS', '0086_auto_20190206_1206'),
    ]

    operations = [
    ]
