# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20180523_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
