# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsInventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManufacturerManifest',
            new_name='ManufactureManifest',
        ),
    ]
