# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsInventory', '0002_auto_20181127_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturemanifest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacturemanifest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ManufactureManifest',
        ),
    ]
